### ISSUE TITLE
Environnement.ts variables not applied

### ISSUE THREAD

**Issue by Dfte** [CMEPW/Smersh#114]
I have an issue when querying Smersh from a domain name and not from 0.0.0.0 or 127.0.0.1. This is related to the CORS configuration which doesn't allow requests to port 8000.

What I tried is to modify the client/src/environments.ts file in which the API/HOSTS variables are set:

![image](https://user-images.githubusercontent.com/23189983/118473741-9ad2e300-b70a-11eb-8e7b-6b64c07ddfc2.png)

After changing those values I rebuilt the containers and for I don't know what reason, the environment variables were not changed in the code:

![image](https://user-images.githubusercontent.com/23189983/118474626-8e02bf00-b70b-11eb-8d12-02cdddbcd322.png)

Even though I rebuilt the containers from scratchs wipping the orphans.

Any idea ? :P

**Comment by Darkweak** [comment]
Hello @Dfte, resolved by #124 :)
