### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by Dfte** [CMEPW/Smersh#17]
Ajouter un onglet timeline récapitulant les vulns trouvées / actions menées et pouvoir exporter la timeline sous la forme d'un PNG.

**Comment by jenaye** [comment]
check it out @Dfte  : 
![image](https://user-images.githubusercontent.com/15458329/108145936-8c096f80-70cc-11eb-92e4-40a8de258a2a.png)

You can set Date + hour + minute and give description of your action 
![image](https://user-images.githubusercontent.com/15458329/108146072-cf63de00-70cc-11eb-8610-e57e9f14304d.png)

i'll work on css later (or not)  but its working  ( see https://github.com/CMEPW/Smersh/pull/20 )
