### ISSUE TITLE
[Feat] - Dark theme

### ISSUE THREAD

**Issue by jenaye** [CMEPW/Smersh#48]

**Comment by Loriage** [comment]
Hello there!
I'm new in open-source projects and it would be a pleasure to work on this issue.
Can I? 

Thanks in advance!

**Comment by jenaye** [comment]
Hi @Loriage! 
It's very nice of you to want to contribute :) 
Unfortunately @sanchis just took care of it and he did a great job, if you feel like it you can always take another issue!
