### ISSUE TITLE
[FEAT] - Translate front-end with i18n

### ISSUE THREAD

**Issue by Darkweak** [CMEPW/Smersh#52]
It could be interesting to translate the app with i18n to be able to scale languages in future without rewriting all the app

**Comment by sanchis** [comment]
Is requisite change the language in runtime? By default i18n for angular create a multiple builds for multiple languages.
If you need to change the language in run time cosider to using [ngx-translate](https://github.com/ngx-translate/core)

**Comment by Darkweak** [comment]
IMO it's better to be able to switch language at runtime because at the moment, API translations are editable for only selected locale (we have to rewrite this part, ping @jenaye)
