### ISSUE TITLE
pre-checked vuln

### ISSUE THREAD

**Issue by Log-s** [CMEPW/Smersh#9]
When adding vulns to a host, these vulns are pre-checked on the next host which causes in some cases display issues.

![image](https://user-images.githubusercontent.com/26695558/107120540-77d49f80-688e-11eb-9149-593d408d499f.png)

**Comment by jenaye** [comment]
![image](https://user-images.githubusercontent.com/15458329/108375465-45b62c80-7202-11eb-82ed-350680396435.png)


I decided to reduce the addition of vuln one by one
